# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github-actions] "
    labels:
      - "housekeeping"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[npm] "
    labels:
      - "housekeeping"
      - "dependencies"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[bundler] "
    labels:
      - "housekeeping"
      - "dependencies"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[gomod] "
    labels:
      - "housekeeping"
      - "dependencies"
